### PR TITLE
add report queue

### PR DESCRIPTION
**Pull request by KLFrost**

### CODE REVIEW

**Comment by toddgardner** [comment]
:+1: 
What are "reports" in this context?

**Comment by KLFrost** [comment]
reports are going to include post-backs, error-backs, and in fact, generic job status-backs...

**Comment by toddgardner** [comment]
One thing I was thinking is you might want some lua to succeed a job and file a new {job|report} atomically, otherwise you risk missing reports or filing multiple, etc.

**Comment by KLFrost** [comment]
yeah, working on this logic now...

**Pull request merged**
